name: Music_Display
channels:
  - defaults
dependencies:
  - annotated-types=0.6.0=py314haa95532_1
  - aom=3.12.1=h00a0c3c_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - contourpy=1.3.3=py314h214f63a_0
  - cycler=0.12.1=py314haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - expat=2.7.4=hd7fb8db_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py314h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=hfbffc0b_0
  - fribidi=1.0.16=haf45083_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=12.3.0=h3ef6528_1
  - icu=73.1=h6c2663c_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.9=py314h03f52e7_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.3.0=h5bd13ec_0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.86.3=h9bccc14_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libmpdec=4.0.0=h827c3e9_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.54=ha15c746_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-base=3.10.8=py314h7ae407a_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py314h0b37514_0
  - mkl_fft=2.1.1=py314h281c9fe_0
  - mkl_random=1.3.0=py314hdbada53_0
  - numpy=2.4.2=py314hbda910b_0
  - numpy-base=2.4.2=py314h11a47e0_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py314haa95532_1
  - pandas=3.0.0=py314hf1216d0_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.1.0=py314h6b7a805_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - pydantic=2.12.4=py314haa95532_0
  - pydantic-core=2.41.5=py314h114bc41_1
  - pyparsing=3.2.5=py314haa95532_0
  - python=3.14.2=h3bc0a5a_101_cp314
  - python-dateutil=2.9.0post0=py314haa95532_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - seaborn=0.13.2=py314haa95532_3
  - setuptools=80.10.2=py314haa95532_0
  - six=1.17.0=py314haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - typing-extensions=4.15.0=py314haa95532_0
  - typing-inspection=0.4.2=py314haa95532_0
  - typing_extensions=4.15.0=py314haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py314haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - musicbrainzngs==0.7.1
prefix: C:\Users\Steven Engelbretson\miniconda3\envs\Music_Display
